// JsFromRoutes CacheKey 946c22ba296cd995b70cfaebd9ca9574
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as staticPages } from '~/api/StaticPagesApi'
export { default as invitations } from '~/api/InvitationsApi'
export { default as plcManufacturers } from '~/api/PlcManufacturersApi'
export { default as plcModels } from '~/api/PlcModelsApi'
export { default as plcs } from '~/api/PlcsApi'
