// JsFromRoutes CacheKey 260969ece64083a53a8e800ec543c537
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/invitations'),
  create: definePathHelper('post', '/invitations'),
  accept: definePathHelper('get', '/invitations/:token/accept'),
}
