// JsFromRoutes CacheKey 0adc40de03f0e6aab6af47fe312637a9
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/plc_manufacturers'),
  create: definePathHelper('post', '/plc_manufacturers'),
  new: definePathHelper('get', '/plc_manufacturers/new'),
  edit: definePathHelper('get', '/plc_manufacturers/:id/edit'),
  get: definePathHelper('get', '/plc_manufacturers/:id'),
  update: definePathHelper('patch', '/plc_manufacturers/:id'),
  destroy: definePathHelper('delete', '/plc_manufacturers/:id'),
}
