// JsFromRoutes CacheKey 43c2bbadb5385bb4a81cf210b3e9dbf6
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/plc_models'),
  create: definePathHelper('post', '/plc_models'),
  new: definePathHelper('get', '/plc_models/new'),
  edit: definePathHelper('get', '/plc_models/:id/edit'),
  get: definePathHelper('get', '/plc_models/:id'),
  update: definePathHelper('patch', '/plc_models/:id'),
  destroy: definePathHelper('delete', '/plc_models/:id'),
}
