// JsFromRoutes CacheKey 0feb82c665128c5431007673f72f8c62
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/plcs'),
  create: definePathHelper('post', '/plcs'),
  new: definePathHelper('get', '/plcs/new'),
  edit: definePathHelper('get', '/plcs/:id/edit'),
  get: definePathHelper('get', '/plcs/:id'),
  update: definePathHelper('patch', '/plcs/:id'),
  destroy: definePathHelper('delete', '/plcs/:id'),
}
