// JsFromRoutes CacheKey 9467400888fa07ef8551243307fc1e77
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  home: definePathHelper('get', '/home'),
  privacyPolicy: definePathHelper('get', '/privacy_policy'),
}
