test:
  HOSTNAME: localhost:3000

  ENABLE_PLC_INGESTION: 'false'
  PLC_INGESTION_BASE_URL: http://localhost:4000
  PLC_INGESTION_SERVICE_API_KEY: AAA
  PLC_INGESTION_CLIENT_API_KEY: BBB

  ENABLE_WRITE_VPN_MANAGER: 'false'
  VPN_MANAGER_BASE_URL: http://localhost:5000
  VPN_MANAGER_API_TOKEN: CCC

development:
  HOSTNAME: localhost:3000

  ENABLE_PLC_INGESTION: 'false'
  PLC_INGESTION_BASE_URL: http://localhost:4000
  PLC_INGESTION_SERVICE_API_KEY: AAA
  PLC_INGESTION_CLIENT_API_KEY: BBB

  ENABLE_WRITE_VPN_MANAGER: 'false'
  VPN_MANAGER_BASE_URL: http://localhost:5000
  VPN_MANAGER_API_TOKEN: CCC
