default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: farm_bits_test
  username: AAA
  password: BBB
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: farm_bits_development
  username: CCC
  password: DDD
  socket: /tmp/mysql.sock
