:concurrency: 5

:queues:
  - [critical, 5]
  - [default, 3]
  - [low, 1]

default_schedule: &default_schedule
  enabled: <%= ENV['RAILS_ENV'] == 'production' ? true : false %>

scheduler:
  schedule:
    plc_polling:
      cron: '*/5 * * * *'
      class: PlcPollingJob
      queue: default

    site_sun_data_sync:
      cron: '0 2 * * *'
      class: SiteSunDataSyncJob
      queue: default

    hourly_aggregation:
      cron: '5 * * * *'
      class: HourlyAggregationJob
      queue: low

    archive:
      cron: '0 3 * * *'
      class: ArchiveJob
      queue: low
