:concurrency: 5

:queues:
  - [critical, 5]
  - [default, 3]
  - [low, 1]

default_schedule: &default_schedule
  enabled: <%= ENV['RAILS_ENV'] == 'production' ? true : false %>

scheduler:
  schedule:
    plc_sync:
      cron: '0 3 * * *'
      class: PlcSyncJob
      queue: critical

    modbus_polling:
      cron: '* * * * *'
      class: ModbusPollingJob
      queue: default

    site_sun_data_sync:
      cron: '0 2 * * *'
      class: SiteSunDataSyncJob
      queue: default

    weather_station_api_ims_fetch:
      cron: "*/10 * * * *"
      class: WeatherStationApiImsFetchJob
      queue: default

    hourly_aggregation:
      cron: '5 * * * *'
      class: HourlyAggregationJob
      queue: low

    weather_station_api_hourly_aggregation:
      cron: "5 * * * *"
      class: WeatherStationApiHourlyAggregationJob
      queue: low

    archive:
      cron: '0 3 * * *'
      class: ArchiveJob
      queue: low
