# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

AdminUser.create([
  name: 'Jeremy Khalfa',
  email: 'jeremy@farm-bits.com',
  password: 'Jeremy123',
  password_confirmation: 'Jeremy123'
])

MeasurementType.create([
  {
    name: 'Weather',
    measurement_subtypes_attributes: [
      { name: 'Temperature',  value_type: 'Instantainus', chart_type: 'Spline', unit: '°C',   color: '' },
      { name: 'Humidity',     value_type: 'Instantainus', chart_type: 'Spline', unit: '%',    color: '' },
      { name: 'Wind Speed',   value_type: 'Instantainus', chart_type: 'Spline', unit: 'm/s',  color: '' },
      { name: 'Rain',         value_type: 'Accumulative', chart_type: 'Bar',    unit: 'mm',   color: '' },
      { name: 'Radiation',    value_type: 'Instantainus', chart_type: 'Spline', unit: 'w/m2', color: '' }
    ]
  },
  {
    name: 'Ambient',
    measurement_subtypes_attributes: [
      { name: 'Temperature',  value_type: 'Instantainus', chart_type: 'Spline', unit: '°C',   color: '' },
      { name: 'Humidity',     value_type: 'Instantainus', chart_type: 'Spline', unit: '%',    color: '' },
      { name: 'CO2',          value_type: 'Instantainus', chart_type: 'Spline', unit: 'ppm',  color: '' }
    ]
  },
  {
    name: 'Soil',
    measurement_subtypes_attributes: [
      { name: 'Temperature',  value_type: 'Instantainus', chart_type: 'Spline', unit: '°C',   color: '' },
      { name: 'Humidity',     value_type: 'Instantainus', chart_type: 'Spline', unit: '%',    color: '' }
    ]
  },
  {
    name: 'Electricity',
    measurement_subtypes_attributes: [
      { name: 'Power',        value_type: 'Instantainus', chart_type: 'Spline', unit: 'W',    color: '' },
      { name: 'Energy',       value_type: 'Accumulative', chart_type: 'Bar',    unit: 'Wh',   color: '' },
      { name: 'Voltage',      value_type: 'Instantainus', chart_type: 'Spline', unit: 'V',    color: '' },
      { name: 'Current',      value_type: 'Instantainus', chart_type: 'Spline', unit: 'A',    color: '' }
    ]
  },
  {
    name: 'Fluid',
    measurement_subtypes_attributes: [
      { name: 'Pressure',     value_type: 'Instantainus', chart_type: 'Spline', unit: 'Bar',  color: '' },
      { name: 'Flow Rate',    value_type: 'Instantainus', chart_type: 'Spline', unit: 'm3/s', color: '' },
      { name: 'Amount',       value_type: 'Accumulative', chart_type: 'Bar',    unit: 'L',    color: '' }
    ]
  },
  {
    name: 'Status',
    measurement_subtypes_attributes: [
      { name: 'Open/Closed',  value_type: 'Instantainus', chart_type: 'Spline', unit: 'O/C',  color: '' },
      { name: 'On/Off',       value_type: 'Instantainus', chart_type: 'Spline', unit: 'OO',   color: '' }
    ]
  }
])

DeviceType.create([
  {
    name: 'Valve',
    communication_type: 'DO',
    color: '#398439',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'Open/Closed')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  {
    name: 'Fan',
    communication_type: 'DO',
    color: '#5C6267',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'On/Off')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  {
    name: 'Heater',
    communication_type: 'DO',
    color: '#FF8C00',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'On/Off')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  {
    name: 'Window',
    communication_type: 'DO',
    color: '#39A0CA',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'Open/Closed')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  {
    name: 'Light',
    communication_type: 'DO',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'On/Off')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  {
    name: 'Humidity Sensor',
    communication_type: 'AI',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'Humidity')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  {
    name: 'Temperatur Sensor',
    communication_type: 'AI',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'Temperature')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  {
    name: 'Pressure Sensor',
    communication_type: 'AI',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'Pressure')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  {
    name: 'Radiation Sensor',
    communication_type: 'AI',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'Radiation')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  {
    name: 'Rain Sensor',
    communication_type: 'AI',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'Rain')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  {
    name: 'Wind Sensor',
    communication_type: 'AI',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'Wind Speed')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  {
    name: 'Water Flow Meter',
    communication_type: 'DI',
    device_type_measurement_subtypes_attributes: MeasurementSubtype.where(name: 'Amount')
      .map { |ms| { measurement_subtype_id: ms.id } }
  },
  #{ name: 'Electrical Meter',   communication_type: 'Modbus RTU' },
  #{ name: 'Weather Station',    communication_type: 'Modbus RTU' }
])

PlcManufacturer.create(
  name: 'Eliwell',
  plc_models_attributes: [
    {
      name: 'FreeAdvance AVC12600/C/L/U/I (AVC126006I500)',
      plc_versions_attributes: [
        {
          name: 'V0',
          registers_attributes: [
            { name: 'Par_TAB', description: 'Tab (map code)', address: 15716, min_value: 0, max_value: 65535 },
            { name: 'Par_POLI', description: 'Polycarbonate code', address: 15717, min_value: 0, max_value: 65535 },
            { name: 'Par_PARMOD', description: 'Parameter modified', address: 15719, min_value: 0, max_value: 1 },
            { name: 'Temp_UM', description: 'Unit of temperature measurement', address: 15725, min_value: 0, max_value: 1 },
            { name: 'Cfg_AI1', description: 'Type of analogue input AI1', address: 15726, min_value: 0, max_value: 11 },
            { name: 'Cfg_AI2', description: 'Type of analogue input AI2', address: 15727, min_value: 0, max_value: 11 },
            { name: 'Cfg_AI3', description: 'Type of analogue input AI3', address: 15728, min_value: 0, max_value: 11 },
            { name: 'Cfg_AI4', description: 'Type of analogue input AI4', address: 15729, min_value: 0, max_value: 11 },
            { name: 'Cfg_AI5', description: 'Type of analogue input AI5', address: 15730, min_value: 0, max_value: 11 },
            { name: 'Cfg_AI6', description: 'Type of analogue input AI6', address: 15731, min_value: 0, max_value: 11 },
            { name: 'Cfg_AI7', description: 'Type of analogue input AI7', address: 16100, min_value: 0, max_value: 11 },
            { name: 'Cfg_AI8', description: 'Type of analogue input AI8', address: 16101, min_value: 0, max_value: 11 },
            { name: 'Calibration_AI1', description: 'Analogue input AI1 differential', address: 15748, min_value: -1000, max_value: 1000 },
            { name: 'Calibration_AI2', description: 'Analogue input AI2 differential', address: 15749, min_value: -1000, max_value: 1000 },
            { name: 'Calibration_AI3', description: 'Analogue input AI3 differential', address: 15750, min_value: -1000, max_value: 1000 },
            { name: 'Calibration_AI4', description: 'Analogue input AI4 differential', address: 15751, min_value: -1000, max_value: 1000 },
            { name: 'Calibration_AI5', description: 'Analogue input AI5 differential', address: 15752, min_value: -1000, max_value: 1000 },
            { name: 'Calibration_AI6', description: 'Analogue input AI6 differential', address: 15753, min_value: -1000, max_value: 1000 },
            { name: 'Calibration_AI7', description: 'Analogue input AI7 differential', address: 16118, min_value: -1000, max_value: 1000 },
            { name: 'Calibration_AI8', description: 'Analogue input AI8 differential', address: 16119, min_value: -1000, max_value: 1000 },
            { name: 'Addr_RS485_OB', description: 'RS485-2 On Board address', address: 15774, min_value: 0, max_value: 255 },
            { name: 'Proto_RS485_OB', description: 'Select RS485-2 On Board protocol', address: 15775, min_value: 2, max_value: 4 },
            { name: 'DataBit_RS485_OB', description: 'RS485-2 On Board Data bit number', address: 15776, min_value: 8, max_value: 8 },
            { name: 'StopBit_RS485_OB', description: 'RS485-2 On Board stop bit number', address: 15777, min_value: 1, max_value: 2 },
            { name: 'Parity_RS485_OB', description: 'RS485-2 On Board parity protocol', address: 15778, min_value: 0, max_value: 2 },
            { name: 'Baud_RS485_OB', description: 'RS485-2 On Board baud rate protocol', address: 15779, min_value: 0, max_value: 5 },
            { name: 'Addr_CAN_OB', description: 'CAN On Board address', address: 15780, min_value: 1, max_value: 127 },
            { name: 'Baud_CAN_OB', description: 'CAN On Board baud rate protocol', address: 15781, min_value: 2, max_value: 6 },
            { name: 'Addr_RS485_PI', description: 'RS485 passive Plug-In address', address: 15782, min_value: 0, max_value: 255 },
            { name: 'Proto_RS485_PI', description: 'Select RS485 passive Plug-In protocol ', address: 15783, min_value: 2, max_value: 4 },
            { name: 'DataBit_RS485_PI', description: 'RS485 passive Plug-In Data bit number', address: 15784, min_value: 8, max_value: 8 },
            { name: 'StopBit_RS485_PI', description: 'RS485 passive Plug-In stop bit number', address: 15785, min_value: 1, max_value: 2 },
            { name: 'Parity_RS485_PI', description: 'RS485 passive Plug-In parity protocol', address: 15786, min_value: 0, max_value: 2 },
            { name: 'Baud_RS485_PI', description: 'RS485 passive Plug-In baud rate protocol', address: 15787, min_value: 0, max_value: 5 },
            { name: 'Addr_CAN_PI', description: 'CAN passive Plug-In address', address: 15788, min_value: 1, max_value: 127 },
            { name: 'Baud_CAN_PI', description: 'CAN Passive Plug-In baud rate protocol', address: 15789, min_value: 2, max_value: 6 },
            { name: 'Addr_RS232_PI', description: 'RS232 passive Plug-In address', address: 15790, min_value: 0, max_value: 255 },
            { name: 'Proto_RS232_PI', description: 'Select RS232 passive Plug-In protocol ', address: 15791, min_value: 2, max_value: 3 },
            { name: 'DataBit_RS232_PI', description: 'RS232 passive Plug-In Data bit number', address: 15792, min_value: 7, max_value: 8 },
            { name: 'StopBit_RS232_PI', description: 'RS232 passive Plug-In stop bit number', address: 15793, min_value: 1, max_value: 2 },
            { name: 'Parity_RS232_PI', description: 'RS232 passive Plug-In parity protocol', address: 15794, min_value: 0, max_value: 2 },
            { name: 'Baud_RS232_PI', description: 'RS232 passive Plug-In baud rate protocol', address: 15795, min_value: 0, max_value: 5 },
            { name: 'Port_FTP_PI', description: 'FTP Port number', address: 15772, min_value: 0, max_value: 65535 },
            { name: 'Port_HTTP_PI', description: 'HTTP Port number', address: 15796, min_value: 0, max_value: 65535 },
            { name: 'Port_ETH_PI', description: 'TCP/IP Port number', address: 15797, min_value: 0, max_value: 65535 },
            { name: 'Ip_1_ETH_PI', description: 'Ethernet IP address (1 st part)', address: 15798, min_value: 0, max_value: 255 },
            { name: 'Ip_2_ETH_PI', description: 'Ethernet IP address (2 nd part)', address: 15799, min_value: 0, max_value: 255 },
            { name: 'Ip_3_ETH_PI', description: 'Ethernet IP address (3 rd part)', address: 15800, min_value: 0, max_value: 255 },
            { name: 'Ip_4_ETH_PI', description: 'Ethernet IP address (4 th part)', address: 15801, min_value: 0, max_value: 255 },
            { name: 'DefGtwy_1_ETH_PI', description: 'Default Gateway (1 st part)', address: 15802, min_value: 0, max_value: 255 },
            { name: 'DefGtwy_2_ETH_PI', description: 'Default Gateway (2 nd part)', address: 15803, min_value: 0, max_value: 255 },
            { name: 'DefGtwy_3_ETH_PI', description: 'Default Gateway (3 rd part)', address: 15804, min_value: 0, max_value: 255 },
            { name: 'DefGtwy_4_ETH_PI', description: 'Default Gateway (4 th part)', address: 15805, min_value: 0, max_value: 255 },
            { name: 'NetMsk_1_ETH_PI', description: 'Net mask (1 st part)', address: 15806, min_value: 0, max_value: 255 },
            { name: 'NetMsk_2_ETH_PI', description: 'Net mask (2 nd part)', address: 15807, min_value: 0, max_value: 255 },
            { name: 'NetMsk_3_ETH_PI', description: 'Net mask (3 rd part)', address: 15808, min_value: 0, max_value: 255 },
            { name: 'NetMsk_4_ETH_PI', description: 'Net mask (4 th part)', address: 15809, min_value: 0, max_value: 255 },
            { name: 'PriDNS_1_ETH_PI', description: 'Primary DNS server (1 st part)', address: 15810, min_value: 0, max_value: 255 },
            { name: 'PriDNS_2_ETH_PI', description: 'Primary DNS server (2 nd part)', address: 15811, min_value: 0, max_value: 255 },
            { name: 'PriDNS_3_ETH_PI', description: 'Primary DNS server (3 rd part)', address: 15812, min_value: 0, max_value: 255 },
            { name: 'PriDNS_4_ETH_PI', description: 'Primary DNS server (4 th part)', address: 15813, min_value: 0, max_value: 255 },
            { name: 'SecDNS_1_ETH_PI', description: 'Secondary DNS server (1 st part)', address: 15814, min_value: 0, max_value: 255 },
            { name: 'SecDNS_2_ETH_PI', description: 'Secondary DNS server (2 nd part)', address: 15815, min_value: 0, max_value: 255 },
            { name: 'SecDNS_3_ETH_PI', description: 'Secondary DNS server (3 rd part)', address: 15816, min_value: 0, max_value: 255 },
            { name: 'SecDNS_4_ETH_PI', description: 'Secondary DNS server (4 th part)', address: 15817, min_value: 0, max_value: 255 },
            { name: 'EnableDHCP_ETH_PI', description: 'Enable DHCP', address: 15818, min_value: 0, max_value: 1 },
            { name: 'Modem_RS232_PI', description: 'Modem Enable', address: 15820, min_value: 0, max_value: 1 },
            { name: 'Modem_InitStr1', description: 'Init String (1st part)', address: 15821 },
            { name: 'Modem_InitStr2', description: 'Init String (2nd part)', address: 15831 },
            { name: 'Modem_HangupStr', description: 'HangUp String', address: 15851 },
            { name: 'Hmi_Language', description: 'Language', address: 15819, min_value: 0, max_value: 65535 },
            { name: 'Par_ContrLCD', description: 'LCD contrast', address: 15723, min_value: 0, max_value: 63 },
            { name: 'Par_BackLightTime', description: 'Backlight time', address: 15724, min_value: 0, max_value: 3600 },
            { name: 'AIL1', description: 'AIL1 analogue input', address: 8336 },
            { name: 'AIL2', description: 'AIL2 analogue input', address: 8337 },
            { name: 'AIL3', description: 'AIL3 analogue input', address: 8338 },
            { name: 'AIL4', description: 'AIL4 analogue input', address: 8339 },
            { name: 'AIL5', description: 'AIL5 analogue input', address: 8340 },
            { name: 'AIL6', description: 'AIL6 analogue input', address: 8341 },
            { name: 'AIL7', description: 'AIL7 analogue input', address: 8342 },
            { name: 'AIL8', description: 'AIL8 analogue input', address: 8343 },
            { name: 'AIL9', description: 'AIL9 analogue input', address: 8344 },
            { name: 'AIL10', description: 'AIL10 analogue input', address: 8345 },
            { name: 'AIL11', description: 'AIL11 analogue input', address: 8346 },
            { name: 'AIL12', description: 'AIL12 analogue input', address: 8347 },
            { name: 'DIL1', description: 'DIL1 digital input', address: 8192, min_value: 0, max_value: 1 },
            { name: 'DIL2', description: 'DIL2 digital input', address: 8193, min_value: 0, max_value: 1 },
            { name: 'DIL3', description: 'DIL3 digital input', address: 8194, min_value: 0, max_value: 1 },
            { name: 'DIL4', description: 'DIL4 digital input', address: 8195, min_value: 0, max_value: 1 },
            { name: 'DIL5', description: 'DIL5 digital input', address: 8196, min_value: 0, max_value: 1 },
            { name: 'DIL6', description: 'DIL6 digital input', address: 8197, min_value: 0, max_value: 1 },
            { name: 'DIL7', description: 'DIL7 digital input', address: 8198, min_value: 0, max_value: 1 },
            { name: 'DIL8', description: 'DIL8 digital input', address: 8199, min_value: 0, max_value: 1 },
            { name: 'DIL9', description: 'DIL9 digital input', address: 8200, min_value: 0, max_value: 1 },
            { name: 'DIL10', description: 'DIL10 digital input', address: 8201, min_value: 0, max_value: 1 },
            { name: 'DIL11', description: 'DIL11 digital input', address: 8202, min_value: 0, max_value: 1 },
            { name: 'DIL12', description: 'DIL12 digital input', address: 8203, min_value: 0, max_value: 1 },
            { name: 'DOL1', description: 'DOL1 digital output', address: 8528, min_value: 0, max_value: 1 },
            { name: 'DOL2', description: 'DOL2 digital output', address: 8529, min_value: 0, max_value: 1 },
            { name: 'DOL3', description: 'DOL3 digital output', address: 8530, min_value: 0, max_value: 1 },
            { name: 'DOL4', description: 'DOL4 digital output', address: 8531, min_value: 0, max_value: 1 },
            { name: 'DOL5', description: 'DOL5 digital output', address: 8532, min_value: 0, max_value: 1 },
            { name: 'DOL6', description: 'DOL6 digital output', address: 8533, min_value: 0, max_value: 1 },
            { name: 'DOL7', description: 'DOL7 digital output', address: 8534, min_value: 0, max_value: 1 },
            { name: 'DOL8', description: 'DOL8 digital output', address: 8535, min_value: 0, max_value: 1 },
            { name: 'DOL9', description: 'DOL9 digital output', address: 8536, min_value: 0, max_value: 1 },
            { name: 'DOL10', description: 'DOL10 digital output', address: 8537, min_value: 0, max_value: 1 },
            { name: 'DOL11', description: 'DOL11 digital output', address: 8538, min_value: 0, max_value: 1 },
            { name: 'DOL12', description: 'DOL12 digital output', address: 8539, min_value: 0, max_value: 1 },
            { name: 'AOL1', description: 'AOL1 analogue output', address: 8448, min_value: 0.0, max_value: 100.0 },
            { name: 'AOL2', description: 'AOL2 analogue output', address: 8449, min_value: 0.0, max_value: 100.0 },
            { name: 'AOL3', description: 'AOL3 analogue output', address: 8450, min_value: 0.0, max_value: 100.0 },
            { name: 'AOL4', description: 'AOL4 analogue output', address: 8451, min_value: 0.0, max_value: 100.0 },
            { name: 'AOL5', description: 'AOL5 analogue output', address: 8452, min_value: 0.0, max_value: 100.0 },
            { name: 'AOL6', description: 'AOL6 analogue output', address: 8453, min_value: 0.0, max_value: 100.0 },
            { name: 'FDI1_counter', description: 'FDI1 input counter', address: 8752 },
            { name: 'FDI1_frequency', description: 'FDI1 input frequency', address: 8754 },
            { name: 'FDI1_value', description: 'FDI1 digital input', address: 8760, min_value: 0, max_value: 1 },
            { name: 'FDI1_reset_counter', description: 'FDI1 reset input counter value', address: 8761, min_value: 0, max_value: 1 },
            { name: 'FDI2_counter', description: 'FDI2 input counter', address: 8898 },
            { name: 'FDI2_frequency', description: 'FDI2 input frequency', address: 8900 },
            { name: 'FDI2_value', description: 'FDI2 digital input', address: 8902, min_value: 0, max_value: 1 },
            { name: 'FDI2_reset_counter', description: 'FDI2 reset input counter value', address: 8903, min_value: 0, max_value: 1 },
            { name: 'LED1', description: 'Led green', address: 8640, min_value: 0, max_value: 2 },
            { name: 'LED2', description: 'Led red', address: 8641, min_value: 0, max_value: 2 },
            { name: 'LED3', description: 'Led yellow', address: 8642, min_value: 0, max_value: 2 },
            { name: 'BACKLIGHT', description: 'Display backlight', address: 8720, min_value: 0, max_value: 4 },
            { name: 'sysClock_seconds', description: 'Second value', address: 8736, min_value: 0, max_value: 59 },
            { name: 'sysClock_minutes', description: 'Minute value', address: 8737, min_value: 0, max_value: 59 },
            { name: 'sysClock_hours', description: 'Hour value', address: 8738, min_value: 0, max_value: 23 },
            { name: 'sysClock_dayweek', description: 'Day of week value', address: 8739, min_value: 0, max_value: 6 },
            { name: 'sysClock_daymonth', description: 'Day of the month value', address: 8740, min_value: 1, max_value: 31 },
            { name: 'sysClock_month', description: 'Month value', address: 8741, min_value: 1, max_value: 12 },
            { name: 'sysClock_year', description: 'Year value', address: 8742, min_value: 10, max_value: 99 },
            { name: 'sysClock_Error', description: 'RTC not inizialized', address: 8743, min_value: 0, max_value: 1 },
            { name: 'sysClockSet_seconds', description: 'Second value (write)', address: 8744, min_value: 0, max_value: 59 },
            { name: 'sysClockSet_minutes', description: 'Minute value (write)', address: 8745, min_value: 0, max_value: 59 },
            { name: 'sysClockSet_hours', description: 'Hour value (write)', address: 8746, min_value: 0, max_value: 23 },
            { name: 'sysClockSet_dayweek', description: 'Day of week value (write)', address: 8747, min_value: 0, max_value: 6 },
            { name: 'sysClockSet_daymonth', description: 'Day of the month value (write)', address: 8748, min_value: 1, max_value: 31 },
            { name: 'sysClockSet_month', description: 'Month value (write)', address: 8749, min_value: 1, max_value: 12 },
            { name: 'sysClockSet_year', description: 'Year value (write)', address: 8750, min_value: 10, max_value: 99 },
            { name: 'sysClockSet_Upload', description: 'RTC upload', address: 8751, min_value: 0, max_value: 1 },
            { name: 'PASSWORD', description: 'Numeric Password for Application protection. Write-only parameter', address: 24320, min_value: 0, max_value: 4294967295 },
            { name: 'Gain_10V_AI1', description: '0-10V calibration gain AI1', address: 15527, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AI10', description: '0-10V calibration gain AI10', address: 15590, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AI11', description: '0-10V calibration gain AI11', address: 15597, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AI12', description: '0-10V calibration gain AI12', address: 15604, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AI2', description: '0-10V calibration gain AI2', address: 15534, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AI3', description: '0-10V calibration gain AI3', address: 15541, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AI4', description: '0-10V calibration gain AI4', address: 15548, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AI5', description: '0-10V calibration gain AI5', address: 15555, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AI6', description: '0-10V calibration gain AI6', address: 15562, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AI7', description: '0-10V calibration gain AI7', address: 15569, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AI8', description: '0-10V calibration gain AI8', address: 15576, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AI9', description: '0-10V calibration gain AI9', address: 15583, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AO1', description: '0-10V calibration gain AO1', address: 15692, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AO2', description: '0-10V calibration gain AO2', address: 15694, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AO3', description: '0-10V calibration gain AO3', address: 15696, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AO4', description: '0-10V calibration gain AO4', address: 15698, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AO5', description: '0-10V calibration gain AO5', address: 15700, min_value: 0, max_value: 65535 },
            { name: 'Gain_10V_AO6', description: '0-10V calibration gain AO6', address: 15702, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI1', description: '0-5Vr calibration gain AI1', address: 15526, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI1', description: '0-5V calibration gain AI1', address: 15529, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI10', description: '0-5Vr calibration gain AI10', address: 15589, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI10', description: '0-5V calibration gain AI10', address: 15592, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI11', description: '0-5Vr calibration gain AI11', address: 15596, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI11', description: '0-5V calibration gain AI11', address: 15599, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI12', description: '0-5Vr calibration gain AI12', address: 15603, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI12', description: '0-5V calibration gain AI12', address: 15606, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI2', description: '0-5Vr calibration gain AI2', address: 15533, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI2', description: '0-5V calibration gain AI2', address: 15536, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI3', description: '0-5Vr calibration gain AI3', address: 15540, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI3', description: '0-5V calibration gain AI3', address: 15543, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI4', description: '0-5Vr calibration gain AI4', address: 15547, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI4', description: '0-5V calibration gain AI4', address: 15550, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI5', description: '0-5Vr calibration gain AI5', address: 15554, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI5', description: '0-5V calibration gain AI5', address: 15557, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI6', description: '0-5Vr calibration gain AI6', address: 15561, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI6', description: '0-5V calibration gain AI6', address: 15564, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI7', description: '0-5Vr calibration gain AI7', address: 15568, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI7', description: '0-5V calibration gain AI7', address: 15571, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI8', description: '0-5Vr calibration gain AI8', address: 15575, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI8', description: '0-5V calibration gain AI8', address: 15578, min_value: 0, max_value: 65535 },
            { name: 'Gain_5Vr_AI9', description: '0-5Vr calibration gain AI9', address: 15582, min_value: 0, max_value: 65535 },
            { name: 'Gain_5V_AI9', description: '0-5V calibration gain AI9', address: 15585, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI1', description: '4-20mA calibration gain AI1', address: 15528, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI10', description: '4-20mA calibration gain AI10', address: 15591, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI11', description: '4-20mA calibration gain AI11', address: 15598, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI12', description: '4-20mA calibration gain AI12', address: 15605, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI2', description: '4-20mA calibration gain AI2', address: 15535, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI3', description: '4-20mA calibration gain AI3', address: 15542, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI4', description: '4-20mA calibration gain AI4', address: 15549, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI5', description: '4-20mA calibration gain AI5', address: 15556, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI6', description: '4-20mA calibration gain AI6', address: 15563, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI7', description: '4-20mA calibration gain AI7', address: 15570, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI8', description: '4-20mA calibration gain AI8', address: 15577, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AI9', description: '4-20mA calibration gain AI9', address: 15584, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AO1', description: '4-20mA calibration gain AO1', address: 15693, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AO2', description: '4-20mA calibration gain AO2', address: 15695, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AO3', description: '4-20mA calibration gain AO3', address: 15697, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AO4', description: '4-20mA calibration gain AO4', address: 15699, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AO5', description: '4-20mA calibration gain AO5', address: 15701, min_value: 0, max_value: 65535 },
            { name: 'Gain_mA_AO6', description: '4-20mA calibration gain AO6', address: 15703, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI1', description: 'NTC calibration gain AI1', address: 15524, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI10', description: 'NTC calibration gain AI10', address: 15587, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI11', description: 'NTC calibration gain AI11', address: 15594, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI12', description: 'NTC calibration gain AI12', address: 15601, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI2', description: 'NTC calibration gain AI2', address: 15531, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI3', description: 'NTC calibration gain AI3', address: 15538, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI4', description: 'NTC calibration gain AI4', address: 15545, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI5', description: 'NTC calibration gain AI5', address: 15552, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI6', description: 'NTC calibration gain AI6', address: 15559, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI7', description: 'NTC calibration gain AI7', address: 15566, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI8', description: 'NTC calibration gain AI8', address: 15573, min_value: 0, max_value: 65535 },
            { name: 'Gain_Ntc_AI9', description: 'NTC calibration gain AI9', address: 15580, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI1', description: 'PT1000 calibration gain AI1', address: 15525, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI10', description: 'PT1000 calibration gain AI10', address: 15588, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI11', description: 'PT1000 calibration gain AI11', address: 15595, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI12', description: 'PT1000 calibration gain AI12', address: 15602, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI2', description: 'PT1000 calibration gain AI2', address: 15532, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI3', description: 'PT1000 calibration gain AI3', address: 15539, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI4', description: 'PT1000 calibration gain AI4', address: 15546, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI5', description: 'PT1000 calibration gain AI5', address: 15553, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI6', description: 'PT1000 calibration gain AI6', address: 15560, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI7', description: 'PT1000 calibration gain AI7', address: 15567, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI8', description: 'PT1000 calibration gain AI8', address: 15574, min_value: 0, max_value: 65535 },
            { name: 'Gain_PT1000_AI9', description: 'PT1000 calibration gain AI9', address: 15581, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI1', description: 'PTC calibration gain AI1', address: 15530, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI10', description: 'PTC calibration gain AI10', address: 15593, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI11', description: 'PTC calibration gain AI11', address: 15600, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI12', description: 'PTC calibration gain AI12', address: 15607, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI2', description: 'PTC calibration gain AI2', address: 15537, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI3', description: 'PTC calibration gain AI3', address: 15544, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI4', description: 'PTC calibration gain AI4', address: 15551, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI5', description: 'PTC calibration gain AI5', address: 15558, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI6', description: 'PTC calibration gain AI6', address: 15565, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI7', description: 'PTC calibration gain AI7', address: 15572, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI8', description: 'PTC calibration gain AI8', address: 15579, min_value: 0, max_value: 65535 },
            { name: 'Gain_PTC_AI9', description: 'PTC calibration gain AI9', address: 15586, min_value: 0, max_value: 65535 },
            { name: 'Offs_Ntc_AI1', description: 'NTC calibration offset AI1', address: 15608, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI1', description: 'PT1000 calibration offset AI1', address: 15609, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI1', description: '0-5Vr calibration offset AI1', address: 15610, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI1', description: '0-10V calibration offset AI1', address: 15611, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI1', description: '4-20mA calibration offset AI1', address: 15612, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI1', description: '0-5V calibration offset AI1', address: 15613, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI1', description: 'PTC calibration offset AI1', address: 15614, min_value: -32768, max_value: 32767 },
            { name: 'Offs_Ntc_AI2', description: 'NTC calibration offset AI2', address: 15615, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI2', description: 'PT1000 calibration offset AI2', address: 15616, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI2', description: '0-5Vr calibration offset AI2', address: 15617, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI2', description: '0-10V calibration offset AI2', address: 15618, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI2', description: '4-20mA calibration offset AI2', address: 15619, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI2', description: '0-5V calibration offset AI2', address: 15620, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI2', description: 'PTC calibration offset AI2', address: 15621, min_value: -32768, max_value: 32767 },
            { name: 'Offs_Ntc_AI3', description: 'NTC calibration offset AI3', address: 15622, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI3', description: 'PT1000 calibration offset AI3', address: 15623, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI3', description: '0-5Vr calibration offset AI3', address: 15624, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI3', description: '0-10V calibration offset AI3', address: 15625, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI3', description: '4-20mA calibration offset AI3', address: 15626, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI3', description: '0-5V calibration offset AI3', address: 15627, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI3', description: 'PTC calibration offset AI3', address: 15628, min_value: -32768, max_value: 32767 },
            { name: 'Offs_Ntc_AI4', description: 'NTC calibration offset AI4', address: 15629, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI4', description: 'PT1000 calibration offset AI4', address: 15630, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI4', description: '0-5Vr calibration offset AI4', address: 15631, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI4', description: '0-10V calibration offset AI4', address: 15632, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI4', description: '4-20mA calibration offset AI4', address: 15633, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI4', description: '0-5V calibration offset AI4', address: 15634, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI4', description: 'PTC calibration offset AI4', address: 15635, min_value: -32768, max_value: 32767 },
            { name: 'Offs_Ntc_AI5', description: 'NTC calibration offset AI5', address: 15636, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI5', description: 'PT1000 calibration offset AI5', address: 15637, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI5', description: '0-5Vr calibration offset AI5', address: 15638, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI5', description: '0-10V calibration offset AI5', address: 15639, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI5', description: '4-20mA calibration offset AI5', address: 15640, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI5', description: '0-5V calibration offset AI5', address: 15641, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI5', description: 'PTC calibration offset AI5', address: 15642, min_value: -32768, max_value: 32767 },
            { name: 'Offs_Ntc_AI6', description: 'NTC calibration offset AI6', address: 15643, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI6', description: 'PT1000 calibration offset AI6', address: 15644, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI6', description: '0-5Vr calibration offset AI6', address: 15645, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI6', description: '0-10V calibration offset AI6', address: 15646, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI6', description: '4-20mA calibration offset AI6', address: 15647, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI6', description: '0-5V calibration offset AI6', address: 15648, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI6', description: 'PTC calibration offset AI6', address: 15649, min_value: -32768, max_value: 32767 },
            { name: 'Offs_Ntc_AI7', description: 'NTC calibration offset AI7', address: 15650, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI7', description: 'PT1000 calibration offset AI7', address: 15651, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI7', description: '0-5Vr calibration offset AI7', address: 15652, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI7', description: '0-10V calibration offset AI7', address: 15653, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI7', description: '4-20mA calibration offset AI7', address: 15654, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI7', description: '0-5V calibration offset AI7', address: 15655, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI7', description: 'PTC calibration offset AI7', address: 15656, min_value: -32768, max_value: 32767 },
            { name: 'Offs_Ntc_AI8', description: 'NTC calibration offset AI8', address: 15657, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI8', description: 'PT1000 calibration offset AI8', address: 15658, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI8', description: '0-5Vr calibration offset AI8', address: 15659, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI8', description: '0-10V calibration offset AI8', address: 15660, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI8', description: '4-20mA calibration offset AI8', address: 15661, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI8', description: '0-5V calibration offset AI8', address: 15662, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI8', description: 'PTC calibration offset AI8', address: 15663, min_value: -32768, max_value: 32767 },
            { name: 'Offs_Ntc_AI9', description: 'NTC calibration offset AI9', address: 15664, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI9', description: 'PT1000 calibration offset AI9', address: 15665, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI9', description: '0-5Vr calibration offset AI9', address: 15666, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI9', description: '0-10V calibration offset AI9', address: 15667, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI9', description: '4-20mA calibration offset AI9', address: 15668, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI9', description: '0-5V calibration offset AI9', address: 15669, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI9', description: 'PTC calibration offset AI9', address: 15670, min_value: -32768, max_value: 32767 },
            { name: 'Offs_Ntc_AI10', description: 'NTC calibration offset AI10', address: 15671, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI10', description: 'PT1000 calibration offset AI10', address: 15672, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI10', description: '0-5Vr calibration offset AI10', address: 15673, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI10', description: '0-10V calibration offset AI10', address: 15674, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI10', description: '4-20mA calibration offset AI10', address: 15675, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI10', description: '0-5V calibration offset AI10', address: 15676, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI10', description: 'PTC calibration offset AI10', address: 15677, min_value: -32768, max_value: 32767 },
            { name: 'Offs_Ntc_AI11', description: 'NTC calibration offset AI11', address: 15678, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI11', description: 'PT1000 calibration offset AI11', address: 15679, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI11', description: '0-5Vr calibration offset AI11', address: 15680, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI11', description: '0-10V calibration offset AI11', address: 15681, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI11', description: '4-20mA calibration offset AI11', address: 15682, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI11', description: '0-5V calibration offset AI11', address: 15683, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI11', description: 'PTC calibration offset AI11', address: 15684, min_value: -32768, max_value: 32767 },
            { name: 'Offs_Ntc_AI12', description: 'NTC calibration offset AI12', address: 15685, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PT1000_AI12', description: 'PT1000 calibration offset AI12', address: 15686, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5Vr_AI12', description: '0-5Vr calibration offset AI12', address: 15687, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AI12', description: '0-10V calibration offset AI12', address: 15688, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AI12', description: '4-20mA calibration offset AI12', address: 15689, min_value: -32768, max_value: 32767 },
            { name: 'Offs_5V_AI12', description: '0-5V calibration offset AI12', address: 15690, min_value: -32768, max_value: 32767 },
            { name: 'Offs_PTC_AI12', description: 'PTC calibration offset AI12', address: 15691, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AO1', description: '0-10V calibration offset AO1', address: 15704, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AO1', description: '4-20mA calibration offset AO1', address: 15705, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AO2', description: '0-10V calibration offset AO2', address: 15706, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AO2', description: '4-20mA calibration offset AO2', address: 15707, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AO3', description: '0-10V calibration offset AO3', address: 15708, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AO3', description: '4-20mA calibration offset AO3', address: 15709, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AO4', description: '0-10V calibration offset AO4', address: 15710, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AO4', description: '4-20mA calibration offset AO4', address: 15711, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AO5', description: '0-10V calibration offset AO5', address: 15712, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AO5', description: '4-20mA calibration offset AO5', address: 15713, min_value: -32768, max_value: 32767 },
            { name: 'Offs_10V_AO6', description: '0-10V calibration offset AO6', address: 15714, min_value: -32768, max_value: 32767 },
            { name: 'Offs_mA_AO6', description: '4-20mA calibration offset AO6', address: 15715, min_value: -32768, max_value: 32767 },
            { name: 'FullScaleMin_AI1', description: 'First value analogue input AI1 scale', address: 15736, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI1', description: 'Last value analogue input AI1 scale', address: 15737, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMin_AI2', description: 'First value analogue input AI2 scale', address: 15738, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI2', description: 'Last value analogue input AI2 scale', address: 15739, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMin_AI3', description: 'First value analogue input AI3 scale', address: 15740, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI3', description: 'Last value analogue input AI3 scale', address: 15741, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMin_AI4', description: 'First value analogue input AI4 scale', address: 15742, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI4', description: 'Last value analogue input AI4 scale', address: 15743, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMin_AI5', description: 'First value analogue input AI5 scale', address: 15744, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI5', description: 'Last value analogue input AI5 scale', address: 15745, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMin_AI6', description: 'First value analogue input AI6 scale', address: 15746, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI6', description: 'Last value analogue input AI6 scale', address: 15747, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMin_AI7', description: 'First value analogue input AI7 scale', address: 16106, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI7', description: 'Last value analogue input AI7 scale', address: 16107, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMin_AI8', description: 'First value analogue input AI8 scale', address: 16108, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI8', description: 'Last value analogue input AI8 scale', address: 16109, min_value: -9999, max_value: 9999 },
            { name: 'Cfg_AO3', description: 'Type of analogue output AO3', address: 15758, min_value: 0, max_value: 3 },
            { name: 'Cfg_AO4', description: 'Type of analogue output AO4', address: 15759, min_value: 0, max_value: 3 },
            { name: 'PWM_frequency_AO3_AO4', description: 'PWM Frequency for AO3 and AO4 in PWM mode', address: 15769, min_value: 0, max_value: 2000 },
            { name: 'PWM_polarity_AO3_AO4', description: 'PWM Polarity for AO3 and AO4 in PWM mode: 1=direct', address: 15770, min_value: 0, max_value: 1 },
            { name: 'Cfg_AI9', description: 'Type of analogue input AI9', address: 16102, min_value: 0, max_value: 11 },
            { name: 'Cfg_AI10', description: 'Type of analogue input AI10', address: 16103, min_value: 0, max_value: 11 },
            { name: 'Cfg_AI11', description: 'Type of analogue input AI11', address: 16104, min_value: 0, max_value: 11 },
            { name: 'Cfg_AI12', description: 'Type of analogue input AI12', address: 16105, min_value: 0, max_value: 11 },
            { name: 'FullScaleMin_AI9', description: 'First value analogue input AI9 scale', address: 16110, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI9', description: 'Last value analogue input AI9 scale', address: 16111, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMin_AI10', description: 'First value analogue input AI10 scale', address: 16112, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI10', description: 'Last value analogue input AI10 scale', address: 16113, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMin_AI11', description: 'First value analogue input AI11 scale', address: 16114, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI11', description: 'Last value analogue input AI11 scale', address: 16115, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMin_AI12', description: 'First value analogue input AI12 scale', address: 16116, min_value: -9999, max_value: 9999 },
            { name: 'FullScaleMax_AI12', description: 'Last value analogue input AI12 scale', address: 16117, min_value: -9999, max_value: 9999 },
            { name: 'Calibration_AI9', description: 'Analogue input AI9 differential', address: 16120, min_value: -1000, max_value: 1000 },
            { name: 'Calibration_AI10', description: 'Analogue input AI10 differential', address: 16121, min_value: -1000, max_value: 1000 },
            { name: 'Calibration_AI11', description: 'Analogue input AI11 differential', address: 16122, min_value: -1000, max_value: 1000 },
            { name: 'Calibration_AI12', description: 'Analogue input AI12 differential', address: 16123, min_value: -1000, max_value: 1000 },
            { name: 'Addr_RS485_OB1', description: 'RS485-1 On Board address', address: 16124, min_value: 0, max_value: 255 },
            { name: 'Proto_RS485_OB1', description: 'Select RS485-1 On Board protocol', address: 16125, min_value: 2, max_value: 4 },
            { name: 'DataBit_RS485_OB1', description: 'RS485-1 On Board Data bit number', address: 16126, min_value: 8, max_value: 8 },
            { name: 'StopBit_RS485_OB1', description: 'RS485-1 On Board stop bit number', address: 16127, min_value: 1, max_value: 2 },
            { name: 'Parity_RS485_OB1', description: 'RS485-1 On Board parity protocol', address: 16128, min_value: 0, max_value: 2 },
            { name: 'Baud_RS485_OB1', description: 'RS485-1 On Board baud rate protocol', address: 16129, min_value: 0, max_value: 5 },
            { name: 'MAC_1_ETH_PI', description: 'MAC address (1 st part)', address: 16130, min_value: 0, max_value: 0 },
            { name: 'MAC_2_ETH_PI', description: 'MAC address (2 nd part)', address: 16131, min_value: 0, max_value: 24 },
            { name: 'MAC_3_ETH_PI', description: 'MAC address (3 rd part)', address: 16132, min_value: 0, max_value: 187 },
            { name: 'MAC_4_ETH_PI', description: 'MAC address (4 th part)', address: 16133, min_value: 0, max_value: 255 },
            { name: 'MAC_5_ETH_PI', description: 'MAC address (5 th part)', address: 16134, min_value: 0, max_value: 255 },
            { name: 'MAC_6_ETH_PI', description: 'MAC address (6 th part)', address: 16135, min_value: 0, max_value: 255 },
            { name: 'HTTP_volume', description: 'Volume of HTTP files', address: 16136, min_value: 0, max_value: 1 },
            { name: 'DAT_volume', description: 'Volume of *.DAT and *.RAW files', address: 16137, min_value: 0, max_value: 1 },
            { name: 'FTP_volume', description: 'Volume of FTP files', address: 16138, min_value: 0, max_value: 1 },
            { name: 'PLC_volume', description: 'Volume of PLC file', address: 16139, min_value: 0, max_value: 1 },
            { name: 'HMI_volume', description: 'Volume of HMI file', address: 16140, min_value: 0, max_value: 1 },
            { name: 'REM_volume', description: 'Volume of HMI Remote file', address: 16141, min_value: 0, max_value: 1 },
            { name: 'PAR_volume', description: 'Volume of CONNEC.PAR file', address: 16142, min_value: 0, max_value: 1 },
            { name: 'microSD_command', description: 'microSD Command', address: 8717, min_value: 0, max_value: 2 },
            { name: 'microSD_status', description: 'Result of microSD command', address: 8718, min_value: 0, max_value: 255 },
            { name: 'microSD_presence', description: 'microSD presence', address: 8719, min_value: 0, max_value: 1 },
            { name: 'USB_Host_command', description: 'USB-Host Command', address: 8756, min_value: 0, max_value: 218 },
            { name: 'USB_Host_status', description: 'Result of USB-Host command', address: 8758, min_value: 0, max_value: 255 },
            { name: 'virtualDipSwitch', description: 'Nemeric prefix for system files name', address: 16143, min_value: 0, max_value: 7 },
            { name: 'Deep_PowerDown_keyword', description: 'Put keyword 12345 to enable deep power down mode at power-off', address: 8716, min_value: 0, max_value: 65535 },
            { name: 'Ip_1_CURRENT', description: 'Ethernet IP address (1 st part)', address: 8764, min_value: 0, max_value: 255 },
            { name: 'Ip_2_CURRENT', description: 'Ethernet IP address (2 nd part)', address: 8765, min_value: 0, max_value: 255 },
            { name: 'Ip_3_CURRENT', description: 'Ethernet IP address (3 rd part)', address: 8766, min_value: 0, max_value: 255 },
            { name: 'Ip_4_CURRENT', description: 'Ethernet IP address (4 th part)', address: 8767, min_value: 0, max_value: 255 },
            { name: 'DefGtwy_1_CURRENT', description: 'Default Gateway (1 st part)', address: 8905, min_value: 0, max_value: 255 },
            { name: 'DefGtwy_2_CURRENT', description: 'Default Gateway (2 nd part)', address: 8906, min_value: 0, max_value: 255 },
            { name: 'DefGtwy_3_CURRENT', description: 'Default Gateway (3 rd part)', address: 8907, min_value: 0, max_value: 255 },
            { name: 'DefGtwy_4_CURRENT', description: 'Default Gateway (4 th part)', address: 8908, min_value: 0, max_value: 255 },
            { name: 'NetMsk_1_CURRENT', description: 'Net mask (1 st part)', address: 8909, min_value: 0, max_value: 255 },
            { name: 'NetMsk_2_CURRENT', description: 'Net mask (2 nd part)', address: 8910, min_value: 0, max_value: 255 },
            { name: 'NetMsk_3_CURRENT', description: 'Net mask (3 rd part)', address: 8911, min_value: 0, max_value: 255 },
            { name: 'NetMsk_4_CURRENT', description: 'Net mask (4 th part)', address: 8912, min_value: 0, max_value: 255 },
            { name: 'PriDNS_1_CURRENT', description: 'Primary DNS server (1 st part)', address: 8913, min_value: 0, max_value: 255 },
            { name: 'PriDNS_2_CURRENT', description: 'Primary DNS server (2 nd part)', address: 8914, min_value: 0, max_value: 255 },
            { name: 'PriDNS_3_CURRENT', description: 'Primary DNS server (3 rd part)', address: 8915, min_value: 0, max_value: 255 },
            { name: 'PriDNS_4_CURRENT', description: 'Primary DNS server (4 th part)', address: 8916, min_value: 0, max_value: 255 },
            { name: 'SecDNS_1_CURRENT', description: 'Secondary DNS server (1 st part)', address: 8917, min_value: 0, max_value: 255 },
            { name: 'SecDNS_2_CURRENT', description: 'Secondary DNS server (2 nd part)', address: 8918, min_value: 0, max_value: 255 },
            { name: 'SecDNS_3_CURRENT', description: 'Secondary DNS server (3 rd part)', address: 8919, min_value: 0, max_value: 255 },
            { name: 'SecDNS_4_CURRENT', description: 'Secondary DNS server (4 th part)', address: 8920, min_value: 0, max_value: 255 },
            { name: 'Load_BACnet_E2_Defaults', description: 'Load default values for BACnet parameters in EEPROM at next boot', address: 15766, min_value: 0, max_value: 1 },
            { name: 'Port_BACnet_IP', description: 'BACnet/IP Port number', address: 15768, min_value: 0, max_value: 65535 },
            { name: 'PushDataIteration', description: '', address: 9007 }
          ]
        }
      ]
    }
  ]
)

interfaces = [
  { name: 'DIL1', communication_type: 'DI' },
  { name: 'DIL2', communication_type: 'DI' },
  { name: 'DIL3', communication_type: 'DI' },
  { name: 'DIL4', communication_type: 'DI' },
  { name: 'DIL5', communication_type: 'DI' },
  { name: 'DIL6', communication_type: 'DI' },
  { name: 'DIL7', communication_type: 'DI' },
  { name: 'DIL8', communication_type: 'DI' },
  { name: 'DIL9', communication_type: 'DI' },
  { name: 'DIL10', communication_type: 'DI' },
  { name: 'DIL11', communication_type: 'DI' },
  { name: 'DIL12', communication_type: 'DI' },
  { name: 'DOL1', communication_type: 'DO' },
  { name: 'DOL2', communication_type: 'DO' },
  { name: 'DOL3', communication_type: 'DO' },
  { name: 'DOL4', communication_type: 'DO' },
  { name: 'DOL5', communication_type: 'DO' },
  { name: 'DOL6', communication_type: 'DO' },
  { name: 'DOL7', communication_type: 'DO' },
  { name: 'DOL8', communication_type: 'DO' },
  { name: 'DOL9', communication_type: 'DO' },
  { name: 'DOL10', communication_type: 'DO' },
  { name: 'DOL11', communication_type: 'DO' },
  { name: 'DOL12', communication_type: 'DO' },
  { name: 'AIL1', communication_type: 'AI' },
  { name: 'AIL2', communication_type: 'AI' },
  { name: 'AIL3', communication_type: 'AI' },
  { name: 'AIL4', communication_type: 'AI' },
  { name: 'AIL5', communication_type: 'AI' },
  { name: 'AIL6', communication_type: 'AI' },
  { name: 'AIL7', communication_type: 'AI' },
  { name: 'AIL8', communication_type: 'AI' },
  { name: 'AIL9', communication_type: 'AI' },
  { name: 'AIL10', communication_type: 'AI' },
  { name: 'AIL11', communication_type: 'AI' },
  { name: 'AIL12', communication_type: 'AI' },
  { name: 'AOL1', communication_type: 'AO' },
  { name: 'AOL2', communication_type: 'AO' },
  { name: 'AOL3', communication_type: 'AO' },
  { name: 'AOL4', communication_type: 'AO' },
  { name: 'AOL5', communication_type: 'AO' },
  { name: 'AOL6', communication_type: 'AO' }
]
interfaces.each do |interface_to_create|
  Register.where(name: interface_to_create[:name]).each do |register|
    Interface.create(
      name: interface_to_create[:name],
      communication_type: interface_to_create[:communication_type],
      register_id: register.id,
      plc_version_id: register.plc_version_id
    )
  end
end

Interface.all.each do |interface|
  interface_nb = interface.name.scan(/\d+/).map(&:to_i)[0]
  Register.where.not(name: interface.name)
    .where('name like ?', "%#{interface.communication_type}#{interface_nb}%")
    .where.not('name like ?', "%#{interface.communication_type}#{interface_nb}0%")
    .where.not('name like ?', "%#{interface.communication_type}#{interface_nb}1%")
    .where.not('name like ?', "%#{interface.communication_type}#{interface_nb}2%")
    .each do |register|
    InterfaceRegister.create(
      interface_id: interface.id,
      register_id: register.id
    )
  end
end

TerminalManufacturer.create(
  name: 'Semtech',
  terminal_models_attributes: [{ name: 'LX40 EMEA' }]
)
